import { NgModule } from '@angular/core'

import {
    MdButtonModule,
    MdCheckboxModule,
    MdToolbarModule,
    MdSidenavModule,
    MdMenuModule,
    MdIconModule,
    MdCardModule,
    MdGridListModule,
    MdListModule,
    MdInputModule,
    MdSnackBarModule,
    MdSlideToggleModule,
    MdTableModule,
    MdSelectModule,
    MdDialogModule,
    MdProgressSpinnerModule,
    MdTooltipModule,
    MdProgressBarModule,
    MdTabsModule,
    MatExpansionModule,
    MatChipsModule,
    MdDatepickerModule,
    MdNativeDateModule
} from '@angular/material'

@NgModule({
    imports: [
        MdButtonModule,
        MdCheckboxModule,
        MdToolbarModule,
        MdSidenavModule,
        MdMenuModule,
        MdIconModule,
        MdCardModule,
        MdGridListModule,
        MdListModule,
        MdInputModule,
        MdSnackBarModule,
        MdSlideToggleModule,
        MdTableModule,
        MdSelectModule,
        MdDialogModule,
        MdProgressSpinnerModule,
        MdTooltipModule,
        MdProgressBarModule,
        MdTabsModule,
        MatExpansionModule,
        MatChipsModule,
        MdDatepickerModule,
        MdNativeDateModule
    ],
    exports: [
        MdButtonModule,
        MdCheckboxModule,
        MdToolbarModule,
        MdSidenavModule,
        MdMenuModule,
        MdIconModule,
        MdCardModule,
        MdGridListModule,
        MdListModule,
        MdInputModule,
        MdSnackBarModule,
        MdSlideToggleModule,
        MdTableModule,
        MdSelectModule,
        MdDialogModule,
        MdProgressSpinnerModule,
        MdTooltipModule,
        MdProgressBarModule,
        MdTabsModule,
        MatExpansionModule,
        MatChipsModule,
        MdDatepickerModule,
        MdNativeDateModule
    ],
    declarations: [],
    providers: [],
})
export class MaterialModule { }
